import { PsikologProfili, BlogYazi } from "@/types";

export const MOCK_PSIKOLOGLAR: PsikologProfili[] = [
  {
    id: "1",
    kullanici_id: "u1",
    unvan: "Uzm. Klinik Psikolog Ayşe Yılmaz",
    hakkinda:
      "İstanbul Üniversitesi Psikoloji bölümü mezunuyum. 10 yılı aşkın süredir klinik psikoloji alanında çalışmaktayım. BDT ve EMDR terapilerinde uzmanlaştım. Danışanlarıma güvenli ve destekleyici bir ortam sunarak, onların kendi potansiyellerini keşfetmelerine yardımcı oluyorum. Özellikle anksiyete bozuklukları, depresyon ve travma sonrası stres bozukluğu alanlarında çalışmaktayım.",
    uzmanlik_alani: ["klinik-psikoloji", "anksiyete", "depresyon", "travma"],
    terapi_yontemi: ["bdt", "emdr"],
    terapi_tipi: "her-ikisi",
    sehir: "İstanbul",
    ilce: "Kadıköy",
    adres: "Caferağa Mah. Moda Cad. No:25 D:5, Kadıköy/İstanbul",
    seans_ucreti: 800,
    online_ucret: 600,
    deneyim_yili: 10,
    egitim: [
      {
        id: "e1",
        okul_adi: "İstanbul Üniversitesi",
        bolum: "Psikoloji",
        derece: "lisans",
        baslangic_yili: 2008,
        bitis_yili: 2012,
        devam_ediyor: false,
      },
      {
        id: "e2",
        okul_adi: "İstanbul Üniversitesi",
        bolum: "Klinik Psikoloji",
        derece: "yuksek-lisans",
        baslangic_yili: 2013,
        bitis_yili: 2016,
        devam_ediyor: false,
      },
    ],
    sertifikalar: [
      {
        id: "s1",
        ad: "BDT Uygulayıcı Sertifikası",
        kurum: "Bilişsel Davranışçı Psikoterapiler Derneği",
        alinma_tarihi: "2017",
        onayli: true,
      },
      {
        id: "s2",
        ad: "EMDR 1. Düzey Sertifikası",
        kurum: "EMDR Derneği",
        alinma_tarihi: "2019",
        onayli: true,
      },
    ],
    rozetler: [
      { id: "r1", tip: "dogrulanmis-uzman", label: "Doğrulanmış Uzman" },
      { id: "r2", tip: "populer", label: "Popüler" },
      { id: "r3", tip: "guvenilir", label: "Güvenilir" },
    ],
    puan_ortalamasi: 4.8,
    yorum_sayisi: 42,
    diploma_onayli: true,
    profil_foto_url: "",
    kapak_foto_url: "",
    abonelik_durumu: "aktif",
    abonelik_paketi: "premium",
    ucretsiz_on_gorusme: true,
    aktif: true,
    created_at: "2024-01-15",
    updated_at: "2024-03-01",
  },
  {
    id: "2",
    kullanici_id: "u2",
    unvan: "Uzm. Psikolog Mehmet Demir",
    hakkinda:
      "Cinsel terapi ve çift terapisi alanında uzmanlaşmış bir psikoloğum. Çiftlerin ve bireylerin ilişki ve cinsellikle ilgili sorunlarını aşmalarına yardımcı oluyorum. Güvenli ve yargısız bir ortamda, danışanlarımın en derin endişelerini paylaşabilecekleri bir alan sunuyorum. 8 yıllık deneyimimle yüzlerce çifte ve bireye destek oldum.",
    uzmanlik_alani: ["cinsel-terapi", "cift-terapisi", "aile-danismanligi"],
    terapi_yontemi: ["psikanalitik", "gestalt"],
    terapi_tipi: "yuz-yuze",
    sehir: "Ankara",
    ilce: "Çankaya",
    adres: "Kızılay Mah. Atatürk Bulvarı No:45 D:12, Çankaya/Ankara",
    seans_ucreti: 1000,
    deneyim_yili: 8,
    egitim: [
      {
        id: "e3",
        okul_adi: "Ankara Üniversitesi",
        bolum: "Psikoloji",
        derece: "lisans",
        baslangic_yili: 2010,
        bitis_yili: 2014,
        devam_ediyor: false,
      },
      {
        id: "e4",
        okul_adi: "Hacettepe Üniversitesi",
        bolum: "Klinik Psikoloji",
        derece: "yuksek-lisans",
        baslangic_yili: 2015,
        bitis_yili: 2018,
        devam_ediyor: false,
      },
    ],
    sertifikalar: [
      {
        id: "s3",
        ad: "Cinsel Terapi Sertifikası",
        kurum: "Cinsel Sağlık Enstitüsü",
        alinma_tarihi: "2019",
        onayli: true,
      },
    ],
    rozetler: [
      { id: "r4", tip: "dogrulanmis-uzman", label: "Doğrulanmış Uzman" },
      { id: "r5", tip: "guvenilir", label: "Güvenilir" },
    ],
    puan_ortalamasi: 4.6,
    yorum_sayisi: 28,
    diploma_onayli: true,
    profil_foto_url: "",
    abonelik_durumu: "aktif",
    abonelik_paketi: "temel",
    ucretsiz_on_gorusme: false,
    aktif: true,
    created_at: "2024-02-01",
    updated_at: "2024-03-10",
  },
  {
    id: "3",
    kullanici_id: "u3",
    unvan: "Çocuk ve Ergen Psikoloğu Zeynep Kaya",
    hakkinda:
      "Çocuk ve ergen psikolojisi alanında 6 yıllık deneyime sahibim. Oyun terapisi, sanat terapisi ve aile danışmanlığı yöntemleriyle çocukların ve gençlerin duygusal, sosyal ve akademik gelişimlerine destek oluyorum. 3-18 yaş aralığındaki çocuk ve ergenlerle çalışıyorum. Ayrıca ebeveyn danışmanlığı hizmeti de vermekteyim.",
    uzmanlik_alani: ["cocuk-psikolojisi", "ergen-psikolojisi", "aile-danismanligi"],
    terapi_yontemi: ["sanat-terapisi", "psikodrama", "farkindalik-temelli"],
    terapi_tipi: "her-ikisi",
    sehir: "İzmir",
    ilce: "Karşıyaka",
    adres: "Atakent Mah. 6540 Sok. No:12 D:3, Karşıyaka/İzmir",
    seans_ucreti: 700,
    online_ucret: 500,
    deneyim_yili: 6,
    egitim: [
      {
        id: "e5",
        okul_adi: "Ege Üniversitesi",
        bolum: "Psikoloji",
        derece: "lisans",
        baslangic_yili: 2012,
        bitis_yili: 2016,
        devam_ediyor: false,
      },
      {
        id: "e6",
        okul_adi: "Dokuz Eylül Üniversitesi",
        bolum: "Çocuk ve Ergen Psikolojisi",
        derece: "yuksek-lisans",
        baslangic_yili: 2017,
        bitis_yili: 2019,
        devam_ediyor: false,
      },
    ],
    sertifikalar: [
      {
        id: "s4",
        ad: "Oyun Terapisi Sertifikası",
        kurum: "Oyun Terapisi Derneği",
        alinma_tarihi: "2020",
        onayli: true,
      },
    ],
    rozetler: [
      { id: "r6", tip: "dogrulanmis-uzman", label: "Doğrulanmış Uzman" },
      { id: "r7", tip: "yeni-uye", label: "Yeni Üye" },
    ],
    puan_ortalamasi: 4.9,
    yorum_sayisi: 15,
    diploma_onayli: true,
    profil_foto_url: "",
    abonelik_durumu: "aktif",
    abonelik_paketi: "premium",
    ucretsiz_on_gorusme: true,
    aktif: true,
    created_at: "2024-03-01",
    updated_at: "2024-03-15",
  },
  {
    id: "4",
    kullanici_id: "u4",
    unvan: "Klinik Psikolog Canan Şahin",
    hakkinda:
      "Travma sonrası stres bozukluğu, anksiyete ve panik atak konularında uzmanlaşmış bir klinik psikoloğum. EMDR terapisinde ileri düzey uygulayıcıyım. Danışanlarıma bilimsel temelli ve bütüncül bir yaklaşım sunuyorum. Online terapi ile Türkiye'nin her yerinden danışan kabul ediyorum.",
    uzmanlik_alani: ["travma", "anksiyete", "depresyon", "klinik-psikoloji"],
    terapi_yontemi: ["emdr", "bdt", "farkindalik-temelli"],
    terapi_tipi: "online",
    sehir: "Online",
    seans_ucreti: 650,
    deneyim_yili: 7,
    egitim: [
      {
        id: "e7",
        okul_adi: "Boğaziçi Üniversitesi",
        bolum: "Psikoloji",
        derece: "lisans",
        baslangic_yili: 2011,
        bitis_yili: 2015,
        devam_ediyor: false,
      },
      {
        id: "e8",
        okul_adi: "İstanbul Üniversitesi",
        bolum: "Klinik Psikoloji",
        derece: "yuksek-lisans",
        baslangic_yili: 2016,
        bitis_yili: 2019,
        devam_ediyor: false,
      },
    ],
    sertifikalar: [
      {
        id: "s5",
        ad: "EMDR İleri Düzey Uygulayıcı",
        kurum: "EMDR Derneği",
        alinma_tarihi: "2021",
        onayli: true,
      },
    ],
    rozetler: [
      { id: "r8", tip: "dogrulanmis-uzman", label: "Doğrulanmış Uzman" },
      { id: "r9", tip: "populer", label: "Popüler" },
    ],
    puan_ortalamasi: 4.7,
    yorum_sayisi: 35,
    diploma_onayli: true,
    profil_foto_url: "",
    abonelik_durumu: "aktif",
    abonelik_paketi: "one-cikan",
    ucretsiz_on_gorusme: true,
    aktif: true,
    created_at: "2024-01-20",
    updated_at: "2024-03-12",
  },
  {
    id: "5",
    kullanici_id: "u5",
    unvan: "Uzm. Psikolog Ali Yıldız",
    hakkinda:
      "Bağımlılık psikolojisi alanında uzmanlaşmış bir psikoloğum. Madde bağımlılığı, alkol bağımlılığı ve davranışsal bağımlılıklar (kumar, internet) konularında bireysel ve grup terapileri düzenliyorum. Yeşilay ile ortak çalışmalar yürütmekteyim. 12 yıllık deneyimimle yüzlerce danışanın bağımlılıkla mücadelesine destek oldum.",
    uzmanlik_alani: ["bagimlilik", "klinik-psikoloji", "depresyon"],
    terapi_yontemi: ["bdt", "dbt", "psikanalitik"],
    terapi_tipi: "yuz-yuze",
    sehir: "Bursa",
    ilce: "Nilüfer",
    adres: "Fethiye Mah. İzmir Yolu Cad. No:78 D:2, Nilüfer/Bursa",
    seans_ucreti: 750,
    deneyim_yili: 12,
    egitim: [
      {
        id: "e9",
        okul_adi: "Uludağ Üniversitesi",
        bolum: "Psikoloji",
        derece: "lisans",
        baslangic_yili: 2006,
        bitis_yili: 2010,
        devam_ediyor: false,
      },
      {
        id: "e10",
        okul_adi: "İstanbul Üniversitesi",
        bolum: "Klinik Psikoloji",
        derece: "doktora",
        baslangic_yili: 2011,
        bitis_yili: 2016,
        devam_ediyor: false,
      },
    ],
    sertifikalar: [
      {
        id: "s6",
        ad: "Bağımlılık Danışmanlığı Sertifikası",
        kurum: "Yeşilay",
        alinma_tarihi: "2017",
        onayli: true,
      },
    ],
    rozetler: [
      { id: "r10", tip: "dogrulanmis-uzman", label: "Doğrulanmış Uzman" },
      { id: "r11", tip: "guvenilir", label: "Güvenilir" },
    ],
    puan_ortalamasi: 4.5,
    yorum_sayisi: 20,
    diploma_onayli: true,
    profil_foto_url: "",
    abonelik_durumu: "aktif",
    abonelik_paketi: "temel",
    ucretsiz_on_gorusme: false,
    aktif: true,
    created_at: "2024-01-10",
    updated_at: "2024-02-20",
  },
  {
    id: "6",
    kullanici_id: "u6",
    unvan: "Nöropsikolog Elif Yıldırım",
    hakkinda:
      "Nöropsikoloji alanında doktora sahibiyim. Dikkat eksikliği, öğrenme güçlükleri, hafıza sorunları ve nörolojik hastalıklara bağlı psikolojik sorunlar üzerine çalışıyorum. Kapsamlı nöropsikolojik değerlendirme ve rehabilitasyon hizmeti sunuyorum. DEHB, otizm spektrum bozukluğu ve özgül öğrenme güçlüğü alanlarında uzmanlaştım.",
    uzmanlik_alani: ["noropsikoloji", "psikolojik-degerlendirme", "klinik-psikoloji"],
    terapi_yontemi: ["bdt", "farkindalik-temelli"],
    terapi_tipi: "her-ikisi",
    sehir: "Antalya",
    ilce: "Muratpaşa",
    adres: "Şirinyalı Mah. 1509 Sok. No:5 D:8, Muratpaşa/Antalya",
    seans_ucreti: 900,
    online_ucret: 700,
    deneyim_yili: 9,
    egitim: [
      {
        id: "e11",
        okul_adi: "Akdeniz Üniversitesi",
        bolum: "Psikoloji",
        derece: "lisans",
        baslangic_yili: 2009,
        bitis_yili: 2013,
        devam_ediyor: false,
      },
      {
        id: "e12",
        okul_adi: "Ankara Üniversitesi",
        bolum: "Nöropsikoloji",
        derece: "doktora",
        baslangic_yili: 2014,
        bitis_yili: 2019,
        devam_ediyor: false,
      },
    ],
    sertifikalar: [
      {
        id: "s7",
        ad: "Nöropsikolojik Test Uygulayıcı Sertifikası",
        kurum: "Nöropsikoloji Derneği",
        alinma_tarihi: "2020",
        onayli: true,
      },
    ],
    rozetler: [
      { id: "r12", tip: "dogrulanmis-uzman", label: "Doğrulanmış Uzman" },
      { id: "r13", tip: "one-cikan", label: "Öne Çıkan" },
    ],
    puan_ortalamasi: 4.4,
    yorum_sayisi: 18,
    diploma_onayli: true,
    profil_foto_url: "",
    abonelik_durumu: "aktif",
    abonelik_paketi: "one-cikan",
    ucretsiz_on_gorusme: true,
    aktif: true,
    created_at: "2024-02-15",
    updated_at: "2024-03-18",
  },
];

export const MOCK_BLOG_YAZILARI: BlogYazi[] = [
  {
    id: "b1",
    psikolog_id: "1",
    psikolog_adi: "Uzm. Klinik Psikolog Ayşe Yılmaz",
    baslik: "Anksiyete ile Başa Çıkmanın 5 Bilimsel Yolu",
    ozet: "Anksiyete bozukluğu ile mücadele edenler için kanıta dayalı yöntemler ve günlük pratik öneriler.",
    icerik: "Anksiyete, modern çağın en yaygın psikolojik sorunlarından biri haline geldi...",
    etiketler: ["anksiyete", "bdt", "farkındalık"],
    okunma_sayisi: 1240,
    yayinda: true,
    created_at: "2024-02-10",
    updated_at: "2024-02-10",
  },
  {
    id: "b2",
    psikolog_id: "2",
    psikolog_adi: "Uzm. Psikolog Mehmet Demir",
    baslik: "Sağlıklı Bir İlişki İçin İletişimin Önemi",
    ozet: "Çift terapisi perspektifinden sağlıklı iletişim kurmanın püf noktaları ve sık yapılan hatalar.",
    icerik: "İlişkilerde iletişim, çoğu zaman sandığımızdan daha karmaşıktır...",
    etiketler: ["çift terapisi", "iletişim", "ilişki"],
    okunma_sayisi: 890,
    yayinda: true,
    created_at: "2024-02-20",
    updated_at: "2024-02-20",
  },
  {
    id: "b3",
    psikolog_id: "3",
    psikolog_adi: "Çocuk ve Ergen Psikoloğu Zeynep Kaya",
    baslik: "Çocuklarda Duygusal Zeka Gelişimi",
    ozet: "Çocukların duygusal zekasını geliştirmek için ebeveynlere özel stratejiler ve oyun temelli yaklaşımlar.",
    icerik: "Duygusal zeka, çocukların gelecekteki başarısında IQ'dan daha belirleyici olabilir...",
    etiketler: ["çocuk psikolojisi", "duygusal zeka", "ebeveynlik"],
    okunma_sayisi: 2100,
    yayinda: true,
    created_at: "2024-03-01",
    updated_at: "2024-03-01",
  },
  {
    id: "b4",
    psikolog_id: "4",
    psikolog_adi: "Klinik Psikolog Canan Şahin",
    baslik: "Travma Sonrası Büyüme: Zorluklardan Güçlenerek Çıkmak",
    ozet: "Travmatik deneyimler sonrası kişisel gelişim ve post-travmatik büyüme kavramı üzerine bir inceleme.",
    icerik: "Travma, yıkıcı etkilerinin yanı sıra beklenmedik bir dönüşüm fırsatı da sunabilir...",
    etiketler: ["travma", "emdr", "kişisel gelişim"],
    okunma_sayisi: 1560,
    yayinda: true,
    created_at: "2024-03-05",
    updated_at: "2024-03-05",
  },
];
